name: BUILD

on:
  schedule:
    - cron:  '0 0 * * SUN'
#  watch:
#    types: [started]
  push:
    branches:
      - 'aur'

jobs:
  build:
    strategy:
      matrix:
        repos: [linux-lqx,yay,linux-xanmod]

      fail-fast: false
      
    runs-on: ubuntu-latest
    
    steps:
    - uses: 135e2/build-aur-action@master
      with:
        repo-name: ${{ matrix.repos }}
    
    - uses: ncipollo/release-action@v1.7.3
      with:
        allowUpdates: true
        tag: "packages"
        artifacts: "./*/*.xz"
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - uses: ncipollo/release-action@v1.7.3
      with:
        allowUpdates: true
        tag: "packages"
        artifacts: "./*/*.zst"
        token: ${{ secrets.GITHUB_TOKEN }}
