name: Build

on:
  push:
    branches:
      - "master"
      - "test"

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux
    steps:
      - name: Setup environment for aurutils
        run: |
          pacman -Sy
          pacman -S base-devel --needed --noconfirm --noprogressbar

          useradd builduser -m
          passwd -d builduser
          echo 'builduser ALL=(ALL) ALL' >> /etc/sudoers
          echo 'root ALL=(ALL) ALL' >> /etc/sudoers
          whoami
          sudo --login --user builduser
          whoami


      - name: Install aurutils
        run: |
          whoami
          su - builduser
          whoami
          curl -O https://aur.archlinux.org/cgit/aur.git/snapshot/aurutils.tar.gz
          tar -xf aurutils.tar.gz
          pushd aurutils
          makepkg -sci

      - name: Set up build environment
        run: |
          su - builduser
          cat << EOF | sudo tee -a /etc/pacman.conf
          [est]
          SigLevel = Optional TrustAll
          Server = file:///home/builduser/localrepo
          EOF

          mkdir localrepo
          repo-add localrepo/est.db.tar.zst
          sudo pacman -Syu

      - name: Build packages
        run: |
          su - builduser
          aur sync miniconda --no-view --no-confirm --rm-deps

      - name: Check
        run: |
          su - builduser
          ls -R localrepo
          cat /etc/pacman.conf
          cat /etc/makepkg.conf
