name: Build

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 20 * * 0,2,4,6" # = CST 4:00 Sun, Tue, Thu and Sat.

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux

    steps:
      - name: Checkout $GITHUB_WORKSPACE
        uses: actions/checkout@v2
        with:
          repository: 135e2/actions_build_aur

      - name: Setup build environment
        env:
          REPO: "135e2"
          GPGKEY: 0F43EA08654E5BCA
        run: ./prepare.sh

      - name: Dirty workaround for unsafe directory (Git v2.35.2)
        run: git config --global --add safe.directory $GITHUB_WORKSPACE #https://github.com/actions/checkout/issues/759
        
      - name: Checkout $GITHUB_WORKSPACE
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Build packages
        env:
          GPGKEY: 0F43EA08654E5BCA
          GPG_PRIVATE_KEY_URL: ${{ secrets.GPG_PRIVATE_KEY_URL }}
          GPG_PRIVATE_KEY_PASSWORD: ${{ secrets.GPG_PRIVATE_KEY_PASSWORD}}
          RCLONE_CONFIG_URL: ${{ secrets.RCLONE_CONFIG_URL }}
        run: ./main.sh
