name: Build

on:
  push:
  schedule:
    - cron: "0 20 * * *" # = CST 4:00

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux

    strategy:
      matrix:
        pkgs:
          - miniconda3
          - fcitx-sogoupinyin

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup build environmnet
        run: bash prepare.sh

      - name: Build packages
        run: sudo -u builduser aur sync ${{ matrix.pkgs }} --no-view --no-confirm --rm-deps

      - name: Check
        run: |
          ls -aR /home/builduser/localrepo
