name: Build

on:
  push:
    branches-ignore:
      - master
  schedule:
    - cron: "0 20 * * *" # = CST 4:00
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux

    steps:
      - name: Checkout $GITHUB_WORKSPACE
        uses: actions/checkout@v2

      - name: Setup build environmnet
        run: ./prepare.sh

      - name: Build packages
        run: ./build.sh

      - name: List packages
        run: ls -1 /home/builduser/localrepo

      - name: Transfer packages
        env:
          RCLONE_CONFIG_URL: ${{ secrets.RCLONE_CONFIG_URL }}
          #REMOTE_REPO: ${{ secrets.REMOTE_REPO }}
        run: ./transfer.sh
