name: Build

on:
  push:
    branches:
      - "master"
      - "test"

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup build environmnet
        run: bash prepare.sh

      - name: Build packages
        run: |
          sudo -u builduser aur sync miniconda3 --no-view --no-confirm --rm-deps
          sudo -u builduser aur sync fcitx-sogoupinyin --no-view --no-confirm --rm-deps

      - name: Check
        run: |
          pwd
          ls -R /home/builduser/localrepo
          cat /etc/pacman.conf
          cat /etc/makepkg.conf
