name: Build

on:
  push:
    branches:
      - "master"
      - "test"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build arch container
        run: |
          docker build -t aurutils .
          docker run -ti --rm aurutils

      - name: Build packages
        run: aur sync miniconda --no-view --no-confirm --rm-deps

      - name: Check
        run: |
          su - builduser
          ls -R localrepo
          cat /etc/pacman.conf
          cat /etc/makepkg.conf
