name: Build

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 20 * * *" # = CST 4:00

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux

    steps:
      - name: Checkout $GITHUB_WORKSPACE
        uses: actions/checkout@v2
        with:
          repository: 135e2/actions_build_aur

      - name: Setup build environmnet
        run: ./prepare.sh

      - name: Dirty workaround for unsafe directory (Git v2.35.2)
        run: git config --global --add safe.directory $GITHUB_WORKSPACE #https://github.com/actions/checkout/issues/759
        
      - name: Checkout $GITHUB_WORKSPACE
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Build packages
        run: ./build.sh
        
      - name: Sign packages
        env:
          GPG_PRIVATE_KEY_URL: ${{ secrets.GPG_PRIVATE_KEY_URL }}
          GPG_PRIVATE_KEY_PASSWORD: ${{ secrets.GPG_PRIVATE_KEY_PASSWORD}}
        run: ./sign.sh

      - name: List packages
        run: ls -1 /home/builduser/localrepo

      - name: Transfer packages
        env:
          RCLONE_CONFIG_URL: ${{ secrets.RCLONE_CONFIG_URL }}
          #REMOTE_REPO: ${{ secrets.REMOTE_REPO }}
        run: ./transfer.sh
